# Generated by Django 5.2.1 on 2025-06-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articulo_imagen_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
